### ISSUE TITLE
Travis builds failing for Python 2.6.9

### ISSUE THREAD

**Issue by curiositycasualty** [bbinet/pillarstack#47]
Correct me if I'm wrong but there's no indication in the travis build of which version of salt is being pulled in by `pip install salt-ssh`. It seems like `2.6` [got deprecated w/ saltstack `2017.7.0`](https://docs.saltstack.com/en/latest/topics/releases/2017.7.0.html#python-2-6-deprecation)

https://travis-ci.org/bbinet/pillarstack/jobs/383973900

```
The command "python test_stack.py" exited with 1.
0.10s$ python test_slashes.py
Traceback (most recent call last):
  File "test_slashes.py", line 4, in <module>
    import stack
  File "/home/travis/build/bbinet/pillarstack/stack.py", line 14, in <module>
    import salt.utils.data
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/salt/utils/data.py", line 18, in <module>
    import salt.utils.stringutils
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/salt/utils/stringutils.py", line 196
    trans_args = ({ord(x): None for x in text_characters},)
                                  ^
SyntaxError: invalid syntax
```

**Comment by bbinet** [comment]
Thank you for the report.
If Salt is not compatible anymore with Python 2.6, then we should actually remove it from travis builds.
